apiVersion: v1
entries:
  prometheus:
  - apiVersion: v1
    appVersion: 2.19.0
    created: "2020-08-17T18:39:25.133452454+08:00"
    dependencies:
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 2.8.*
    description: Prometheus is a monitoring system and time series database.
    digest: 461bdda38b5495d3e043a2b6ee3d5177ea3010b273d8a8ea341ef188b61e2070
    home: https://prometheus.io/
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    maintainers:
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    name: prometheus
    sources:
    - https://github.com/prometheus/alertmanager
    - https://github.com/prometheus/prometheus
    - https://github.com/prometheus/pushgateway
    - https://github.com/prometheus/node_exporter
    - https://github.com/kubernetes/kube-state-metrics
    urls:
    - https:https://github.com/Jiacheng123Wang/chart_gi
    version: 11.11.1
generated: "2020-08-17T18:39:25.128204673+08:00"
